<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'ac0dd655be35124af58b6da0fb19ec63',
  'DATABASE_URL' => 'mysql://petya:root@symfony-app-nginx-mysql:3306/test?serverVersion=8&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'null://null',
);
